from __future__ import annotations

import bisect
import math

from river import base
from river.utils.vectordict import euclidean_distance_dict


class SOStream(base.Clusterer):
    r"""SOStream

    The SOStream algorithm [^1] is inspired by DBSCAN (Density-Based Spatial Clustering
    of Applications with Noise) and SOM (Self Organizing Maps). It can adapt its threshold
    due to dynamic learning process based on the idea of building neighborhoods with a
    minimum number of points. The micro-clusters that are formed after shrinking are used
    as a representative of the global cluster. The shrinking procedure also helps to
    correctly identify highly-overlapped clusters. As a result, the clusters become less
    sensitive to outliers. All aspects of SOStream (including deletion, addition, merging,
    and fading of clusters) are performed online.

    For a new point `p`:

    * Find the winning micro cluster, that is the one whose center is closest to `p`.

    * Calculate the radius of the winning micro cluster, which is the distance to
    its `min_pts`-th nearest neighbor. If d(p, winner) <= radius, then `p` is considered
    a point in the winning micro cluster. Otherwise, a new micro cluster is created with `p`
    as its center.

    * The neighborhood of the winning micro cluster is updated by moving neighbors clusters
    towards the winner, applying self-organizing map learning rule. The neighbor that overlaps
    with the winner is merged into it.


    Parameters
    ----------
    alpha
        The SOStream algorithm uses this parameter as a scaling factor to the
        step by which a neighbor is moved towards the winner.
    min_pts
        Minimum number of neighbor micro clusters (including the winner) to
        derive the adaptive radius.
    merge_threshold
        Determine the threshold to merge two micro clusters. If the distance
        between two micro clusters is less than or equal to this threshold,
        they are merged.
    fading_factor
        Parameter that controls the importance of historical data to current cluster.
        Note that `fading_factor` has to be different from `0`.
    fade_threshold
        The threshold to remove a micro cluster. If the weight of a micro cluster is
        less than or equal to this threshold, it is removed.
    fading_interval
        The interval at which the fading process is applied, counted in samples and
        independent of `stream_speed`. Set it to 0 to disable the sweep.
    stream_speed
        Number of point arriving in one time unit. This parameter supports the process
        of verifying with paper experiments. Default value is 1 in case of not mentioning.

    Attributes
    ----------
    n_clusters
        Number of clusters generated by the algorithm.
    micro_clusters
        Micro clusters generated by the algorithm. Instead of updating directly the new instance points
        into a nearest micro cluster, through each iteration, the weight and center will be modified
        so that the clusters are closer to the new points, using the Gaussian neighborhood function.
    centers
        Final clusters' centers.

    References
    ----------
    [^1]: Isaksson, C., Dunham, M. H., & Hahsler, M. (2012). SOStream: Self
          Organizing Density-Based Clustering over Data Stream. In Machine
          Learning and Data Mining in Pattern Recognition, LNAI 7376,
          pp. 264-278. Springer.

    Examples
    --------

    >>> from river import cluster
    >>> from river import stream

    >>> X = [
    ...     [1, 0.5], [1, 0.625], [1, 0.75], [1, 1.125], [1, 1.5], [1, 1.75],
    ...     [4, 1.5], [4, 2.25], [4, 2.5], [4, 3], [4, 3.25], [4, 3.5]
    ... ]

    >>> sostream = cluster.SOStream(
    ...     alpha=0.1,
    ...     min_pts=2,
    ...     merge_threshold=1.0,
    ...     fading_factor=0.01,
    ...     fade_threshold=0.1,
    ...     fading_interval=100
    ... )

    >>> for x, _ in stream.iter_array(X):
    ...     sostream.learn_one(x)

    >>> sostream.n_clusters
    3

    >>> sostream.predict_one({0: 1, 1: 2})
    3

    >>> sostream.predict_one({0: 5, 1: 3})
    4
    """

    def __init__(
        self,
        alpha: float = 0.1,
        min_pts: int = 2,
        merge_threshold: float = 0.1,
        fading_factor: float = 0.1,
        fade_threshold: float = 0.1,
        fading_interval: int = 100,
        stream_speed: int = 1,
    ):
        super().__init__()
        self.alpha = alpha
        self.min_pts = min_pts
        self.merge_threshold = merge_threshold
        self.fading_factor = fading_factor
        self.fade_threshold = fade_threshold
        self.fading_interval = fading_interval
        self.stream_speed = stream_speed

        self._time_stamp = 0
        self._n_samples_seen = 0
        self._next_id = 0
        self._keys: list = []
        self._positions: dict = {}
        self._micro_clusters: dict[int, SOStreamMicroCluster] = {}

    def _vectorize(self, x):
        positions = self._positions
        keys = self._keys
        fresh = [k for k in x if k not in positions]
        if fresh:
            try:
                fresh.sort()
            except TypeError:
                fresh.sort(key=repr)
            for k in fresh:
                positions[k] = len(keys)
                keys.append(k)
            for micro_cluster in self._micro_clusters.values():
                micro_cluster.grow(keys)
        return {k: float(x.get(k, 0.0)) for k in keys}

    def _project(self, x):
        return {k: float(x.get(k, 0.0)) for k in self._keys}

    @staticmethod
    def _distance(point_a, point_b):
        return euclidean_distance_dict(point_a, point_b)

    def _find_winner(self, values):
        winner_id = -1
        winner_distance = math.inf
        for i, micro_cluster in self._micro_clusters.items():
            distance = euclidean_distance_dict(micro_cluster.center, values)
            if distance < winner_distance:
                winner_distance = distance
                winner_id = i
        return winner_id, winner_distance

    def _find_neighbors(self, winner_id):
        micro_clusters = self._micro_clusters
        winner = micro_clusters[winner_id]
        center = winner.center
        distances = {
            i: euclidean_distance_dict(center, micro_cluster.center)
            for i, micro_cluster in micro_clusters.items()
        }
        ordered = sorted(distances.values())
        k_distance = ordered[0]
        for _ in range(self.min_pts - 1):
            index = bisect.bisect_right(ordered, k_distance)
            if index == len(ordered):
                break
            k_distance = ordered[index]
        winner.radius = k_distance
        neighbors = [i for i, distance in distances.items() if distance <= k_distance]
        if len(neighbors) > 1:
            neighbors.sort(key=distances.__getitem__)
        return neighbors

    def _new_cluster(self, values, weight):
        new_id = self._next_id
        self._next_id = new_id + 1
        self._micro_clusters[new_id] = SOStreamMicroCluster(
            values=values,
            weight=weight,
            last_update=self._time_stamp,
        )

    def _update_cluster(self, winner_id, values, neighbor_ids, weight):
        micro_clusters = self._micro_clusters
        winner = micro_clusters[winner_id]
        winner_radius = winner.radius

        winner.fade(self._time_stamp, self.fading_factor)
        winner.insert(values, weight)

        if winner_radius <= 0.0:
            return

        width = 2.0 * winner_radius * winner_radius
        winner_center = winner.center
        alpha = self.alpha
        for i in neighbor_ids:
            if i == winner_id:
                continue
            center = micro_clusters[i].center
            influence = math.exp(-euclidean_distance_dict(center, winner_center) / width)
            factor = alpha * influence
            for j, c_j in center.items():
                center[j] = c_j + factor * (winner_center[j] - c_j)

    def _find_overlap(self, winner_id, neighbor_ids):
        micro_clusters = self._micro_clusters
        winner = micro_clusters[winner_id]
        center = winner.center
        radius = winner.radius
        overlap = []
        for i in neighbor_ids:
            if i == winner_id:
                continue
            other = micro_clusters[i]
            if euclidean_distance_dict(center, other.center) - (radius + other.radius) < 0.0:
                overlap.append(i)
        return overlap

    def _merge_clusters(self, winner_id, overlap):
        micro_clusters = self._micro_clusters
        winner = micro_clusters[winner_id]
        merge_threshold = self.merge_threshold
        timestamp = self._time_stamp
        fading_factor = self.fading_factor
        for i in overlap:
            other = micro_clusters[i]
            if euclidean_distance_dict(winner.center, other.center) < merge_threshold:
                winner.fade(timestamp, fading_factor)
                other.fade(timestamp, fading_factor)
                winner.merge(other)
                del micro_clusters[i]

    def _fade_all(self):
        micro_clusters = self._micro_clusters
        timestamp = self._time_stamp
        fading_factor = self.fading_factor
        fade_threshold = self.fade_threshold
        for i in list(micro_clusters):
            micro_cluster = micro_clusters[i]
            micro_cluster.fade(timestamp, fading_factor)
            if micro_cluster.weight < fade_threshold:
                del micro_clusters[i]

    def learn_one(self, x, w=1.0):
        values = self._vectorize(x)

        if len(self._micro_clusters) >= self.min_pts:
            winner_id, winner_distance = self._find_winner(values)
            neighbor_ids = self._find_neighbors(winner_id)
            if winner_distance <= self._micro_clusters[winner_id].radius:
                self._update_cluster(winner_id, values, neighbor_ids, w)
            else:
                self._new_cluster(values, w)
            overlap = self._find_overlap(winner_id, neighbor_ids)
            if overlap:
                self._merge_clusters(winner_id, overlap)
        else:
            self._new_cluster(values, w)

        self._n_samples_seen += 1
        if self._n_samples_seen % self.stream_speed == 0:
            self._time_stamp += 1
        if self.fading_interval and self._n_samples_seen % self.fading_interval == 0:
            self._fade_all()

    def predict_one(self, x, w=None):
        values = self._project(x)
        label = 0
        best_distance = math.inf
        for i, micro_cluster in self._micro_clusters.items():
            distance = euclidean_distance_dict(micro_cluster.center, values)
            if distance < best_distance:
                best_distance = distance
                label = i
        return label

    @property
    def n_clusters(self) -> int:
        return len(self._micro_clusters)

    @property
    def micro_clusters(self) -> dict[int, SOStreamMicroCluster]:
        return self._micro_clusters

    @property
    def clusters(self) -> dict[int, SOStreamMicroCluster]:
        return self._micro_clusters

    @property
    def centers(self) -> dict:
        return {i: micro_cluster.center for i, micro_cluster in self._micro_clusters.items()}


class SOStreamMicroCluster:
    __slots__ = ("center", "last_update", "radius", "weight")

    def __init__(self, values, weight, last_update):
        self.center = dict(values)
        self.weight = weight
        self.radius = 0.0
        self.last_update = last_update

    def grow(self, keys) -> None:
        center = self.center
        for k in keys:
            if k not in center:
                center[k] = 0.0

    def fade(self, timestamp, fading_factor) -> None:
        elapsed = timestamp - self.last_update
        if elapsed > 0 and fading_factor > 0.0:
            self.weight *= math.pow(2.0, -fading_factor * elapsed)
        self.last_update = timestamp

    def insert(self, values, weight) -> None:
        total = self.weight + weight
        if total <= 0.0:
            return
        center = self.center
        share = weight / total
        for j, v_j in values.items():
            center[j] += share * (v_j - center[j])
        self.weight = total

    def merge(self, other: SOStreamMicroCluster) -> None:
        total = self.weight + other.weight
        if total <= 0.0:
            return
        center = self.center
        other_center = other.center
        merged = {
            j: (self.weight * c_j + other.weight * other_center[j]) / total
            for j, c_j in center.items()
        }
        self.radius = max(
            euclidean_distance_dict(merged, center) + self.radius,
            euclidean_distance_dict(merged, other_center) + other.radius,
        )
        self.center = merged
        self.weight = total
